package(default_visibility = ["//visibility:public"])

load("//tools:embed.bzl", "embed_data")

embed_data(
  name = "app",
  srcs = [
    "image/appicon.ico",
    "external/material.js",
    "external/material.css",
    "external/material-icons.css",
    "external/material-icons.woff2",
    "external/preact.js",
    "external/preact-mdl.js",
    "lib/sling.js",
  ],
)
