package(default_visibility = ["//visibility:public"])

cc_library(
  name = "companies-house",
  srcs = ["companies-house.cc"],
  deps = [
    "//sling/base",
    "//sling/frame",
    "//sling/task",
    "//sling/task:frames",
    "//sling/task:mapper",
    "//sling/task:reducer",
  ],
  alwayslink = 1,
)
