package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "parser-test",
  srcs = ["parser-test.cc"],
  deps = [
    "//base",
    "//file:posix",
    "//nlp/document",
    "//nlp/document:document-tokenizer",
    "//nlp/parser",
  ],
)

