# -*- coding: utf-8 -*-

import sling
import sling.task.corpora
import sling.flags as flags
import sys

flags.parse()

# Initialize knowledge base.
kb = sling.Store()
kb.load("local/data/e/wiki/kb.sling")
n_qua = kb["is"]
n_lang = kb["lang"]
n_instance_of = kb["P31"]
n_unit_symbol = kb["P5061"]
n_si_base_unit = kb["Q223662"]
n_si_derived_unit = kb["Q208469"]

# Unit types.
unit_types = {
  kb["Q1371562"],    # unit of area
  kb["Q10387685"],   # unit of density
  kb["Q2916980"],    # unit of energy
  kb["Q15976022"],   # unit of force
  kb["Q1978718"],    # unit of length
  kb["Q3647172"],    # unit of mass
  kb["Q15222637"],   # unit of speed
  kb["Q2394680"],    # unit of temperature
  kb["Q1302471"],    # unit of volume
  kb["Q4173969"],    # unit of pressure
  kb["Q10387689"],   # unit of power

  kb["Q13587321"],   # unit of angle
  kb["Q16604158"],   # unit of charge
  kb["Q1790144"],    # unit of time
  kb["Q2360980"],    # unit of amount
}

# SI unit prefixes.
si_prefixes = [
  ("Y", 1e24, "yotta"),
  ("Z", 1e21, "zetta"),
  ("E", 1e18, "exa"),
  ("P", 1e15, "peta"),
  ("T", 1e12, "tera"),
  ("G", 1e9, "giga"),
  ("M", 1e6, "mega"),
  ("k", 1e3, "kilo"),
  ("h", 1e2, "hecto"),
  ("da", 1e1, "deca"),
  ("d", 1e-1, "deci"),
  ("c", 1e-2, "centi"),
  ("m", 1e-3, "milli"),
  ("μ", 1e-6, "milli"),
  ("u", 1e-6, "micro"),
  ("n", 1e-9, "nano"),
  ("p", 1e-12, "pico"),
  ("f", 1e-15, "femto"),
  ("a", 1e-18, "atto"),
  ("z", 1e-21, "zepto"),
  ("y", 1e-24, "yocto"),
]

# Black-listed unknown that conflict with other more important units.
blacklist = [
  kb["Q27949241"],  # R vs Réaumur
  kb["Q1396128"],   # faraday (F) vs Fahrenheit
  kb["Q25406"],     # coulomb (C) vs Celcius
  kb["Q1798227"],   # decimal degree (°) vs arcdegree
  kb["Q217208"],    # Julian year (a) vs are
  kb["Q1092296"],   # annum (a) vs are
  kb["Q12714022"],  # short hundredweight (cwt) vs barrel
  kb["Q32751296"],  # dry barrel (bbl) vs are
  kb["Q2642547"],   # hectoannum (ha) vs hectare
  kb["Q39360471"],  # nautical leagues (nl) vs nanolitre
  kb["Q23925410"],  # UK gallon (gal) vs US gallon
  kb["Q1472674"],   # svedberg (S) vs spat
  kb["Q577"],       # curtis (a) vs year
  kb["Q39462709"],  # square inches (in2) vs square inch
  kb["Q1086691"],   # frigorie (fg) vs femtogram
  kb["Q37732658"],  # rankine (°R) vs réaumur
  kb["Q420266"],    # UK fluid ounce (fl oz) vs US fluid ounce
]

# Trim unit.
def trim_unit(unit):
  if unit == "°": return unit
  unit = unit.replace("²", "2")
  unit = unit.replace("³", "3")
  unit = unit.replace("°", "")
  return unit

# Escape string.
def escape(s):
  return s.replace('"', '\\"')

# Create output file.
language = kb["/lang/" + flags.arg.language]
f = open("data/wiki/units-" + language.code + ".sling", "w")
f.write("; Units for " + language.name + " (" + language.code + ").\n")
f.write("; Generated by " + sys.argv[0] + ".\n")
f.write("{=/w/units/" + language.code + "\n")

units = {}
si_units = []

# Find all units in the knowledge base.
for item in kb:
  # Check if item is a unit.
  is_unit = False
  for t in item(n_instance_of):
    if t in unit_types: is_unit = True
  if not is_unit: continue
  if item in blacklist: continue

  # Check if it is a SI unit.
  si = False
  for t in item(n_instance_of):
    if t == n_si_base_unit or t == n_si_derived_unit:
      si = True
  if si: si_units.append(item)

  # Output units for each language here we have a unit symbol.
  for symbol in item(n_unit_symbol):
    unit = symbol
    lang = None
    while type(unit) is not str:
      lang = unit[n_lang]
      unit = unit[n_qua]

    unit = trim_unit(unit)
    if lang != language and lang != None: continue

    #print "unit:", unit
    if unit in units:
      print "Ambiguity:", unit, units[unit].id, "vs", item.id
    else:
      f.write('  "' + escape(unit) + '": {/w/unit: ' + item.id +
              ' name: \"' + item.name + '"}\n')
      units[unit] = item

# Add units with SI prefixes.
for item in si_units:
  for symbol in item(n_unit_symbol):
    unit = symbol
    lang = None
    while type(unit) is not str:
      lang = unit[n_lang]
      unit = unit[n_qua]

    unit = trim_unit(unit)
    if lang != language and lang != None: continue

    for prefix, factor, name in si_prefixes:
      punit = prefix + unit
      if punit not in units:
        f.write('  "' + escape(punit) + '": {/w/unit: ' + item.id +
                ' name: "' + name + item.name + '"' +
                ' /w/amount: ' + str(factor) + '}\n')
        units[punit] = item

f.write("}\n")
f.close()

