package(default_visibility = ["//visibility:public"])

cc_library(
  name = "socket-server",
  srcs = ["socket-server.cc"],
  hdrs = ["socket-server.h"],
  deps = [
    "//sling/base",
    "//sling/file",
    "//sling/util:mutex",
    "//sling/util:thread",
  ],
)

